### ISSUE TITLE
List of (y/i)earn UX improvements from forum

### ISSUE THREAD

**Issue by milkyklim** [iearn-finance/ygov-finance#4]
I've asked people for feedback and received pretty long list: https://gov.yearn.finance/t/time-to-get-our-shit-together/173/9. 

Should I put each bullet point as separate issue in this repo or will you take over from forum? 

cc @antonnell

**Comment by antonnell** [comment]
1) Each iearn product is on its own website, there’s no central repo or index where I can see all iearn products in one simple interface (I really do like the simple design). I think https://yearn.finance 4 should be this central index for yearn, ygov, staking, yswap, ytrade, yliquidate, ypool, and hyperlinks to integrations like curve 1inch, forum, docs, twitter, medium, FAQ, YFI explainer, etc.
2) The voting page on https://ygov.finance/vote 3 does not make it clear that you need 1000 bpt in the governance pool staked, it does not tell you what each proposal is for, there should be a link to the proposal from this forum and at least the title of the vote, and the UI does not prevent people from voting even when they don’t meet the requirements, wasting their gas
3) Each staking pool should have the steps laid out in on how to join and the hyperlinks to each pool on curve and balancer, or at least link to an article that explains what you need to do to farm YFI and provide liquidity
4) https://iearn.finance and https://docs.iearn.finance are dead links, I’ve seen people think the project is dead because they had these bookmarked before the rebrand to yearn, these should redirect to their correct links (https://yearn.finance 4 and https://docs.yearn.finance 1) like how https://uniwap.exchange goes to https://app.uniswap.org 1. Thus we should stay consistent with the name from here on out for continued brand recognition (We should converage on Yearn, yEarn, or yearn?)
5) When I refresh the page on iearn sites, it makes me sign into my web3 wallet again
6) UI on https://ygov.finance 2 doesn’t update when I make a transaction like deposting, withdrawing, claiming, means I need to refresh and connect my wallet again
7) https://docs.yearn.finance 1 should have a link to the twitter and medium blog
8) There should be a security page/section that explains that the protocol is community governed and the admin key is a 6-of-9 multisig and moving to DAO in the future
9) Its not clear how the system works, or all the components. Nothing is actually documented

Alrighty:
1) Anybody in the community with some competent design capabilities can create a marketing related website. And we can look at getting it domained. If needs be, I can build whatever they design. But this isn't a massive priority.
2) There isn't a requirement like that. You need 1000 BTP to stake in the Fee Rewards pool.
3) I'll add in the links
4) We don't control those domains anymore - legal reasons. So can't redirect.
5) I don't want to store any session information. With the balances refreshing it shouldn't be as much of a hastle.
6) Added a refresh every 15 seconds. If I missed somewhere, let me know and Ill fix.
7) Asked Andre to update.
8) This can be added to the "Marketing website (1)"
9) There are some medium articles explaining how the systems work. 

With regards to 1, 8, 9. Our goal was never to make this massively normy friendly. If you don't want to go through the effort of reading how the system works (medium, twitter, reading smart contracts) then sadly you are going to miss out. Everything in the yearn ecosystem is designed to make our lives easier.

**Comment by antonnell** [comment]
Anyone in the community is welcome to submit PR's to the websites adding more info or whatever they feel is necessary.
If it doesn't encroach on the ease-of-use, then I'll probably merge it in.

If how to use the ecosystem is unclear, write up an article on medium, I'm sure Andre will publish it if it is up to his standards and credit the user.

**Comment by milkyklim** [comment]
Anton, thanks for thorough answers. 

Do you mind if I open issues and then ask people from community to fix them? Not really expecting you to take care of them 😅

**Comment by antonnell** [comment]
Yea sure

**Comment by DBBIONIC** [comment]
Thanks @antonnell . One suggestion that I've seen come up is embedding a live quorum % tracker as part of each proposal on voting dashboard. Currently quorum for a proposal to have a qualifying vote is set at 30% but the community doesn't have visibility on what that means based on the quantum of BPT staked/voted.

**Comment by brockelmore** [comment]
Re: 5 - like any at all? All it requires is something like `localStorage.set("connectedBefore", true)` so that the UI knows that Metamask has been approved already so it can connect automatically? I don't care too much but I am curious why the hard rule? 

I'm happy to contribute on some of these things

**Comment by antonnell** [comment]
> Re: 5

I added an auto connect to injected provider.
in e5b2975aaa595f1708e874476aa84c75023349cc
